export const PunchOfImages = [
  {
    src: "/assets/imgs/chair1.png",
    alt: "Sign up image",
    title: "Cantilever chair",
    code: "Y523201",
    price: "42.00",
  },
  {
    src: "/assets/imgs/chair2.png",
    alt: "Login image",
    title: "Cantilever chair",
    code: "Y523201",
    price: "42.00",
  },
  {
    src: "/assets/imgs/chair3.png",
    alt: "Forget password image",
    title: "Cantilever chair",
    code: "Y523201",
    price: "42.00",
  },
  {
    src: "/assets/imgs/chair4.png",
    alt: "Sign up image",
    title: "Cantilever chair",
    code: "Y523201",
    price: "42.00",
  },
  {
    src: "/assets/imgs/chair5.png",
    alt: "Login image",
    title: "Cantilever chair",
    code: "Y523201",
    price: "42.00",
  },
  {
    src: "/assets/imgs/chair6.png",
    alt: "Forget password image",
    title: "Cantilever chair",
    code: "Y523201",
    price: "42.00",
  },
  {
    src: "/assets/imgs/chair7.png",
    alt: "Sign up image",
    title: "Cantilever chair",
    code: "Y523201",
    price: "42.00",
  },
  {
    src: "/assets/imgs/chair8.png",
    alt: "Login image",
    title: "Cantilever chair",
    code: "Y523201",
    price: "42.00",
  },
  {
    src: "/assets/imgs/chair9.png",
    alt: "Forget password image",
    title: "Cantilever chair",
    code: "Y523201",
    price: "42.00",
  },
  {
    src: "/assets/imgs/chair3.png",
    alt: "Sign up image",
    title: "Cantilever chair",
    code: "Y523201",
    price: "42.00",
  },
  {
    src: "/assets/imgs/chair7.png",
    alt: "Login image",
    title: "Cantilever chair",
    code: "Y523201",
    price: "42.00",
  },
  {
    src: "/assets/imgs/chair1.png",
    alt: "Forget password image",
    title: "Cantilever chair",
    code: "Y523201",
    price: "42.00",
  },
  {
    src: "/assets/imgs/chair2.png",
    alt: "Sign up image",
    title: "Cantilever chair",
    code: "Y523201",
    price: "42.00",
  },
  {
    src: "/assets/imgs/chair8.png",
    alt: "Login image",
    title: "Cantilever chair",
    code: "Y523201",
    price: "42.00",
  },
  {
    src: "/assets/imgs/chair6.png",
    alt: "Forget password image",
    title: "Cantilever chair",
    code: "Y523201",
    price: "42.00",
  },
];
